# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhuangyan/projects/CPP/da4qi4/daqi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhuangyan/projects/CPP/da4qi4/daqi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhuangyan/projects/CPP/da4qi4/daqi/CMakeFiles /home/zhuangyan/projects/CPP/da4qi4/daqi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhuangyan/projects/CPP/da4qi4/daqi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named da4qi4

# Build rule for target.
da4qi4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 da4qi4
.PHONY : da4qi4

# fast build rule for target.
da4qi4/fast:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/build
.PHONY : da4qi4/fast

#=============================================================================
# Target rules for targets named Include

# Build rule for target.
Include: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Include
.PHONY : Include

# fast build rule for target.
Include/fast:
	$(MAKE) -f CMakeFiles/Include.dir/build.make CMakeFiles/Include.dir/build
.PHONY : Include/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousSubmit.dir/build.make nlohmann_json/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousMemCheck.dir/build.make nlohmann_json/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousConfigure.dir/build.make nlohmann_json/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalSubmit.dir/build.make nlohmann_json/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalMemCheck.dir/build.make nlohmann_json/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalTest.dir/build.make nlohmann_json/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousTest.dir/build.make nlohmann_json/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousUpdate.dir/build.make nlohmann_json/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalBuild.dir/build.make nlohmann_json/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyMemoryCheck.dir/build.make nlohmann_json/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyBuild.dir/build.make nlohmann_json/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalUpdate.dir/build.make nlohmann_json/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousBuild.dir/build.make nlohmann_json/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/Continuous.dir/build.make nlohmann_json/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/Experimental.dir/build.make nlohmann_json/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalConfigure.dir/build.make nlohmann_json/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyStart.dir/build.make nlohmann_json/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyTest.dir/build.make nlohmann_json/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyUpdate.dir/build.make nlohmann_json/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousCoverage.dir/build.make nlohmann_json/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalStart.dir/build.make nlohmann_json/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/Nightly.dir/build.make nlohmann_json/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyConfigure.dir/build.make nlohmann_json/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyCoverage.dir/build.make nlohmann_json/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ExperimentalCoverage.dir/build.make nlohmann_json/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlyMemCheck.dir/build.make nlohmann_json/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/ContinuousStart.dir/build.make nlohmann_json/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f nlohmann_json/CMakeFiles/NightlySubmit.dir/build.make nlohmann_json/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

application.o: application.cpp.o

.PHONY : application.o

# target to build an object file
application.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/application.cpp.o
.PHONY : application.cpp.o

application.i: application.cpp.i

.PHONY : application.i

# target to preprocess a source file
application.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/application.cpp.i
.PHONY : application.cpp.i

application.s: application.cpp.s

.PHONY : application.s

# target to generate assembly for a file
application.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/application.cpp.s
.PHONY : application.cpp.s

connection.o: connection.cpp.o

.PHONY : connection.o

# target to build an object file
connection.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/connection.cpp.o
.PHONY : connection.cpp.o

connection.i: connection.cpp.i

.PHONY : connection.i

# target to preprocess a source file
connection.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/connection.cpp.i
.PHONY : connection.cpp.i

connection.s: connection.cpp.s

.PHONY : connection.s

# target to generate assembly for a file
connection.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/connection.cpp.s
.PHONY : connection.cpp.s

context.o: context.cpp.o

.PHONY : context.o

# target to build an object file
context.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/context.cpp.o
.PHONY : context.cpp.o

context.i: context.cpp.i

.PHONY : context.i

# target to preprocess a source file
context.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/context.cpp.i
.PHONY : context.cpp.i

context.s: context.cpp.s

.PHONY : context.s

# target to generate assembly for a file
context.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/context.cpp.s
.PHONY : context.cpp.s

cookie.o: cookie.cpp.o

.PHONY : cookie.o

# target to build an object file
cookie.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/cookie.cpp.o
.PHONY : cookie.cpp.o

cookie.i: cookie.cpp.i

.PHONY : cookie.i

# target to preprocess a source file
cookie.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/cookie.cpp.i
.PHONY : cookie.cpp.i

cookie.s: cookie.cpp.s

.PHONY : cookie.s

# target to generate assembly for a file
cookie.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/cookie.cpp.s
.PHONY : cookie.cpp.s

def/boost_def.o: def/boost_def.cpp.o

.PHONY : def/boost_def.o

# target to build an object file
def/boost_def.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/boost_def.cpp.o
.PHONY : def/boost_def.cpp.o

def/boost_def.i: def/boost_def.cpp.i

.PHONY : def/boost_def.i

# target to preprocess a source file
def/boost_def.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/boost_def.cpp.i
.PHONY : def/boost_def.cpp.i

def/boost_def.s: def/boost_def.cpp.s

.PHONY : def/boost_def.s

# target to generate assembly for a file
def/boost_def.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/boost_def.cpp.s
.PHONY : def/boost_def.cpp.s

def/def.o: def/def.cpp.o

.PHONY : def/def.o

# target to build an object file
def/def.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/def.cpp.o
.PHONY : def/def.cpp.o

def/def.i: def/def.cpp.i

.PHONY : def/def.i

# target to preprocess a source file
def/def.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/def.cpp.i
.PHONY : def/def.cpp.i

def/def.s: def/def.cpp.s

.PHONY : def/def.s

# target to generate assembly for a file
def/def.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/def.cpp.s
.PHONY : def/def.cpp.s

def/json_def.o: def/json_def.cpp.o

.PHONY : def/json_def.o

# target to build an object file
def/json_def.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/json_def.cpp.o
.PHONY : def/json_def.cpp.o

def/json_def.i: def/json_def.cpp.i

.PHONY : def/json_def.i

# target to preprocess a source file
def/json_def.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/json_def.cpp.i
.PHONY : def/json_def.cpp.i

def/json_def.s: def/json_def.cpp.s

.PHONY : def/json_def.s

# target to generate assembly for a file
def/json_def.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/json_def.cpp.s
.PHONY : def/json_def.cpp.s

def/log_def.o: def/log_def.cpp.o

.PHONY : def/log_def.o

# target to build an object file
def/log_def.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/log_def.cpp.o
.PHONY : def/log_def.cpp.o

def/log_def.i: def/log_def.cpp.i

.PHONY : def/log_def.i

# target to preprocess a source file
def/log_def.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/log_def.cpp.i
.PHONY : def/log_def.cpp.i

def/log_def.s: def/log_def.cpp.s

.PHONY : def/log_def.s

# target to generate assembly for a file
def/log_def.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/log_def.cpp.s
.PHONY : def/log_def.cpp.s

def/redis_def.o: def/redis_def.cpp.o

.PHONY : def/redis_def.o

# target to build an object file
def/redis_def.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/redis_def.cpp.o
.PHONY : def/redis_def.cpp.o

def/redis_def.i: def/redis_def.cpp.i

.PHONY : def/redis_def.i

# target to preprocess a source file
def/redis_def.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/redis_def.cpp.i
.PHONY : def/redis_def.cpp.i

def/redis_def.s: def/redis_def.cpp.s

.PHONY : def/redis_def.s

# target to generate assembly for a file
def/redis_def.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/def/redis_def.cpp.s
.PHONY : def/redis_def.cpp.s

handler.o: handler.cpp.o

.PHONY : handler.o

# target to build an object file
handler.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/handler.cpp.o
.PHONY : handler.cpp.o

handler.i: handler.cpp.i

.PHONY : handler.i

# target to preprocess a source file
handler.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/handler.cpp.i
.PHONY : handler.cpp.i

handler.s: handler.cpp.s

.PHONY : handler.s

# target to generate assembly for a file
handler.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/handler.cpp.s
.PHONY : handler.cpp.s

http-parser/http_parser.o: http-parser/http_parser.c.o

.PHONY : http-parser/http_parser.o

# target to build an object file
http-parser/http_parser.c.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/http-parser/http_parser.c.o
.PHONY : http-parser/http_parser.c.o

http-parser/http_parser.i: http-parser/http_parser.c.i

.PHONY : http-parser/http_parser.i

# target to preprocess a source file
http-parser/http_parser.c.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/http-parser/http_parser.c.i
.PHONY : http-parser/http_parser.c.i

http-parser/http_parser.s: http-parser/http_parser.c.s

.PHONY : http-parser/http_parser.s

# target to generate assembly for a file
http-parser/http_parser.c.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/http-parser/http_parser.c.s
.PHONY : http-parser/http_parser.c.s

intercepter.o: intercepter.cpp.o

.PHONY : intercepter.o

# target to build an object file
intercepter.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepter.cpp.o
.PHONY : intercepter.cpp.o

intercepter.i: intercepter.cpp.i

.PHONY : intercepter.i

# target to preprocess a source file
intercepter.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepter.cpp.i
.PHONY : intercepter.cpp.i

intercepter.s: intercepter.cpp.s

.PHONY : intercepter.s

# target to generate assembly for a file
intercepter.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepter.cpp.s
.PHONY : intercepter.cpp.s

intercepters/session_redis.o: intercepters/session_redis.cpp.o

.PHONY : intercepters/session_redis.o

# target to build an object file
intercepters/session_redis.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepters/session_redis.cpp.o
.PHONY : intercepters/session_redis.cpp.o

intercepters/session_redis.i: intercepters/session_redis.cpp.i

.PHONY : intercepters/session_redis.i

# target to preprocess a source file
intercepters/session_redis.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepters/session_redis.cpp.i
.PHONY : intercepters/session_redis.cpp.i

intercepters/session_redis.s: intercepters/session_redis.cpp.s

.PHONY : intercepters/session_redis.s

# target to generate assembly for a file
intercepters/session_redis.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepters/session_redis.cpp.s
.PHONY : intercepters/session_redis.cpp.s

intercepters/static_file.o: intercepters/static_file.cpp.o

.PHONY : intercepters/static_file.o

# target to build an object file
intercepters/static_file.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepters/static_file.cpp.o
.PHONY : intercepters/static_file.cpp.o

intercepters/static_file.i: intercepters/static_file.cpp.i

.PHONY : intercepters/static_file.i

# target to preprocess a source file
intercepters/static_file.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepters/static_file.cpp.i
.PHONY : intercepters/static_file.cpp.i

intercepters/static_file.s: intercepters/static_file.cpp.s

.PHONY : intercepters/static_file.s

# target to generate assembly for a file
intercepters/static_file.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/intercepters/static_file.cpp.s
.PHONY : intercepters/static_file.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/main.cpp.s
.PHONY : main.cpp.s

multipart-parser/multipart_parser.o: multipart-parser/multipart_parser.c.o

.PHONY : multipart-parser/multipart_parser.o

# target to build an object file
multipart-parser/multipart_parser.c.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/multipart-parser/multipart_parser.c.o
.PHONY : multipart-parser/multipart_parser.c.o

multipart-parser/multipart_parser.i: multipart-parser/multipart_parser.c.i

.PHONY : multipart-parser/multipart_parser.i

# target to preprocess a source file
multipart-parser/multipart_parser.c.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/multipart-parser/multipart_parser.c.i
.PHONY : multipart-parser/multipart_parser.c.i

multipart-parser/multipart_parser.s: multipart-parser/multipart_parser.c.s

.PHONY : multipart-parser/multipart_parser.s

# target to generate assembly for a file
multipart-parser/multipart_parser.c.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/multipart-parser/multipart_parser.c.s
.PHONY : multipart-parser/multipart_parser.c.s

redis_client.o: redis_client.cpp.o

.PHONY : redis_client.o

# target to build an object file
redis_client.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/redis_client.cpp.o
.PHONY : redis_client.cpp.o

redis_client.i: redis_client.cpp.i

.PHONY : redis_client.i

# target to preprocess a source file
redis_client.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/redis_client.cpp.i
.PHONY : redis_client.cpp.i

redis_client.s: redis_client.cpp.s

.PHONY : redis_client.s

# target to generate assembly for a file
redis_client.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/redis_client.cpp.s
.PHONY : redis_client.cpp.s

request.o: request.cpp.o

.PHONY : request.o

# target to build an object file
request.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/request.cpp.o
.PHONY : request.cpp.o

request.i: request.cpp.i

.PHONY : request.i

# target to preprocess a source file
request.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/request.cpp.i
.PHONY : request.cpp.i

request.s: request.cpp.s

.PHONY : request.s

# target to generate assembly for a file
request.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/request.cpp.s
.PHONY : request.cpp.s

response.o: response.cpp.o

.PHONY : response.o

# target to build an object file
response.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/response.cpp.o
.PHONY : response.cpp.o

response.i: response.cpp.i

.PHONY : response.i

# target to preprocess a source file
response.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/response.cpp.i
.PHONY : response.cpp.i

response.s: response.cpp.s

.PHONY : response.s

# target to generate assembly for a file
response.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/response.cpp.s
.PHONY : response.cpp.s

router.o: router.cpp.o

.PHONY : router.o

# target to build an object file
router.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/router.cpp.o
.PHONY : router.cpp.o

router.i: router.cpp.i

.PHONY : router.i

# target to preprocess a source file
router.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/router.cpp.i
.PHONY : router.cpp.i

router.s: router.cpp.s

.PHONY : router.s

# target to generate assembly for a file
router.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/router.cpp.s
.PHONY : router.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/server.cpp.s
.PHONY : server.cpp.s

server_engine.o: server_engine.cpp.o

.PHONY : server_engine.o

# target to build an object file
server_engine.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/server_engine.cpp.o
.PHONY : server_engine.cpp.o

server_engine.i: server_engine.cpp.i

.PHONY : server_engine.i

# target to preprocess a source file
server_engine.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/server_engine.cpp.i
.PHONY : server_engine.cpp.i

server_engine.s: server_engine.cpp.s

.PHONY : server_engine.s

# target to generate assembly for a file
server_engine.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/server_engine.cpp.s
.PHONY : server_engine.cpp.s

session.o: session.cpp.o

.PHONY : session.o

# target to build an object file
session.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/session.cpp.o
.PHONY : session.cpp.o

session.i: session.cpp.i

.PHONY : session.i

# target to preprocess a source file
session.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/session.cpp.i
.PHONY : session.cpp.i

session.s: session.cpp.s

.PHONY : session.s

# target to generate assembly for a file
session.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/session.cpp.s
.PHONY : session.cpp.s

templates.o: templates.cpp.o

.PHONY : templates.o

# target to build an object file
templates.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/templates.cpp.o
.PHONY : templates.cpp.o

templates.i: templates.cpp.i

.PHONY : templates.i

# target to preprocess a source file
templates.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/templates.cpp.i
.PHONY : templates.cpp.i

templates.s: templates.cpp.s

.PHONY : templates.s

# target to generate assembly for a file
templates.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/templates.cpp.s
.PHONY : templates.cpp.s

utilities/asio_utilities.o: utilities/asio_utilities.cpp.o

.PHONY : utilities/asio_utilities.o

# target to build an object file
utilities/asio_utilities.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/asio_utilities.cpp.o
.PHONY : utilities/asio_utilities.cpp.o

utilities/asio_utilities.i: utilities/asio_utilities.cpp.i

.PHONY : utilities/asio_utilities.i

# target to preprocess a source file
utilities/asio_utilities.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/asio_utilities.cpp.i
.PHONY : utilities/asio_utilities.cpp.i

utilities/asio_utilities.s: utilities/asio_utilities.cpp.s

.PHONY : utilities/asio_utilities.s

# target to generate assembly for a file
utilities/asio_utilities.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/asio_utilities.cpp.s
.PHONY : utilities/asio_utilities.cpp.s

utilities/captcha_utilities.o: utilities/captcha_utilities.cpp.o

.PHONY : utilities/captcha_utilities.o

# target to build an object file
utilities/captcha_utilities.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/captcha_utilities.cpp.o
.PHONY : utilities/captcha_utilities.cpp.o

utilities/captcha_utilities.i: utilities/captcha_utilities.cpp.i

.PHONY : utilities/captcha_utilities.i

# target to preprocess a source file
utilities/captcha_utilities.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/captcha_utilities.cpp.i
.PHONY : utilities/captcha_utilities.cpp.i

utilities/captcha_utilities.s: utilities/captcha_utilities.cpp.s

.PHONY : utilities/captcha_utilities.s

# target to generate assembly for a file
utilities/captcha_utilities.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/captcha_utilities.cpp.s
.PHONY : utilities/captcha_utilities.cpp.s

utilities/file_utilities.o: utilities/file_utilities.cpp.o

.PHONY : utilities/file_utilities.o

# target to build an object file
utilities/file_utilities.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/file_utilities.cpp.o
.PHONY : utilities/file_utilities.cpp.o

utilities/file_utilities.i: utilities/file_utilities.cpp.i

.PHONY : utilities/file_utilities.i

# target to preprocess a source file
utilities/file_utilities.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/file_utilities.cpp.i
.PHONY : utilities/file_utilities.cpp.i

utilities/file_utilities.s: utilities/file_utilities.cpp.s

.PHONY : utilities/file_utilities.s

# target to generate assembly for a file
utilities/file_utilities.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/file_utilities.cpp.s
.PHONY : utilities/file_utilities.cpp.s

utilities/html_utilities.o: utilities/html_utilities.cpp.o

.PHONY : utilities/html_utilities.o

# target to build an object file
utilities/html_utilities.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/html_utilities.cpp.o
.PHONY : utilities/html_utilities.cpp.o

utilities/html_utilities.i: utilities/html_utilities.cpp.i

.PHONY : utilities/html_utilities.i

# target to preprocess a source file
utilities/html_utilities.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/html_utilities.cpp.i
.PHONY : utilities/html_utilities.cpp.i

utilities/html_utilities.s: utilities/html_utilities.cpp.s

.PHONY : utilities/html_utilities.s

# target to generate assembly for a file
utilities/html_utilities.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/html_utilities.cpp.s
.PHONY : utilities/html_utilities.cpp.s

utilities/string_utilities.o: utilities/string_utilities.cpp.o

.PHONY : utilities/string_utilities.o

# target to build an object file
utilities/string_utilities.cpp.o:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/string_utilities.cpp.o
.PHONY : utilities/string_utilities.cpp.o

utilities/string_utilities.i: utilities/string_utilities.cpp.i

.PHONY : utilities/string_utilities.i

# target to preprocess a source file
utilities/string_utilities.cpp.i:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/string_utilities.cpp.i
.PHONY : utilities/string_utilities.cpp.i

utilities/string_utilities.s: utilities/string_utilities.cpp.s

.PHONY : utilities/string_utilities.s

# target to generate assembly for a file
utilities/string_utilities.cpp.s:
	$(MAKE) -f CMakeFiles/da4qi4.dir/build.make CMakeFiles/da4qi4.dir/utilities/string_utilities.cpp.s
.PHONY : utilities/string_utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... da4qi4"
	@echo "... rebuild_cache"
	@echo "... Include"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousConfigure"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyStart"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalStart"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... application.o"
	@echo "... application.i"
	@echo "... application.s"
	@echo "... connection.o"
	@echo "... connection.i"
	@echo "... connection.s"
	@echo "... context.o"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... cookie.o"
	@echo "... cookie.i"
	@echo "... cookie.s"
	@echo "... def/boost_def.o"
	@echo "... def/boost_def.i"
	@echo "... def/boost_def.s"
	@echo "... def/def.o"
	@echo "... def/def.i"
	@echo "... def/def.s"
	@echo "... def/json_def.o"
	@echo "... def/json_def.i"
	@echo "... def/json_def.s"
	@echo "... def/log_def.o"
	@echo "... def/log_def.i"
	@echo "... def/log_def.s"
	@echo "... def/redis_def.o"
	@echo "... def/redis_def.i"
	@echo "... def/redis_def.s"
	@echo "... handler.o"
	@echo "... handler.i"
	@echo "... handler.s"
	@echo "... http-parser/http_parser.o"
	@echo "... http-parser/http_parser.i"
	@echo "... http-parser/http_parser.s"
	@echo "... intercepter.o"
	@echo "... intercepter.i"
	@echo "... intercepter.s"
	@echo "... intercepters/session_redis.o"
	@echo "... intercepters/session_redis.i"
	@echo "... intercepters/session_redis.s"
	@echo "... intercepters/static_file.o"
	@echo "... intercepters/static_file.i"
	@echo "... intercepters/static_file.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... multipart-parser/multipart_parser.o"
	@echo "... multipart-parser/multipart_parser.i"
	@echo "... multipart-parser/multipart_parser.s"
	@echo "... redis_client.o"
	@echo "... redis_client.i"
	@echo "... redis_client.s"
	@echo "... request.o"
	@echo "... request.i"
	@echo "... request.s"
	@echo "... response.o"
	@echo "... response.i"
	@echo "... response.s"
	@echo "... router.o"
	@echo "... router.i"
	@echo "... router.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... server_engine.o"
	@echo "... server_engine.i"
	@echo "... server_engine.s"
	@echo "... session.o"
	@echo "... session.i"
	@echo "... session.s"
	@echo "... templates.o"
	@echo "... templates.i"
	@echo "... templates.s"
	@echo "... utilities/asio_utilities.o"
	@echo "... utilities/asio_utilities.i"
	@echo "... utilities/asio_utilities.s"
	@echo "... utilities/captcha_utilities.o"
	@echo "... utilities/captcha_utilities.i"
	@echo "... utilities/captcha_utilities.s"
	@echo "... utilities/file_utilities.o"
	@echo "... utilities/file_utilities.i"
	@echo "... utilities/file_utilities.s"
	@echo "... utilities/html_utilities.o"
	@echo "... utilities/html_utilities.i"
	@echo "... utilities/html_utilities.s"
	@echo "... utilities/string_utilities.o"
	@echo "... utilities/string_utilities.i"
	@echo "... utilities/string_utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

